services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'cuvantar'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
